"""
SPENDLY — Dashboard
====================
Person 2 responsibility: integrate all team outputs into one Streamlit app.

Run from the spendly/ root:
    streamlit run dashboard/app.py

Expects these files to exist (generated by teammates):
    outputs/anomaly_df.csv       ← Person 3 (patterns.py)
    outputs/cluster_labels.csv   ← Person 3 (patterns.py)
    outputs/forecast.csv         ← Person 4 (forecast.py)
    outputs/training_loss.png    ← Person 4 (forecast.py)
    models/rf_model.pkl          ← Person 2 (categorise.py)
    data/processed/train.csv     ← Person 1 (preprocess.py)
"""

import os
import json
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use("Agg")
import streamlit as st

# -- Optional imports (graceful fallback if not installed) -------------------
try:
    import joblib
    JOBLIB_OK = True
except ImportError:
    JOBLIB_OK = False

try:
    import plotly.express as px
    import plotly.graph_objects as go
    PLOTLY_OK = True
except ImportError:
    PLOTLY_OK = False

# -- Path helpers ------------------------------------------------------------
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUTPUTS_DIR = os.path.join(REPO_ROOT, "outputs")
MODELS_DIR = os.path.join(REPO_ROOT, "models")
DATA_DIR = os.path.join(REPO_ROOT, "data", "processed")


def _path(*parts):
    return os.path.join(REPO_ROOT, *parts)


def _read_csv(rel_path: str) -> pd.DataFrame | None:
    full = _path(rel_path)
    if not os.path.exists(full):
        return None
    try:
        return pd.read_csv(full)
    except Exception:
        return None


# -- Page config -------------------------------------------------------------
st.set_page_config(
    page_title="SPENDLY Dashboard",
    page_icon="💳",
    layout="wide",
    initial_sidebar_state="expanded",
)

# -- Custom CSS --------------------------------------------------------------
st.markdown("""
<style>
    .metric-card {
        background: #f8f9fa;
        border-radius: 10px;
        padding: 16px 20px;
        border-left: 4px solid #667eea;
        margin-bottom: 8px;
    }
    .metric-value { font-size: 28px; font-weight: 700; color: #1a1a2e; }
    .metric-label { font-size: 13px; color: #666; margin-top: 2px; }
    .section-header {
        font-size: 16px; font-weight: 600;
        padding: 6px 0 10px; color: #1a1a2e;
        border-bottom: 2px solid #667eea;
        margin-bottom: 16px;
    }
    .status-ok  { color: #28a745; font-weight: 600; }
    .status-bad { color: #dc3545; font-weight: 600; }
</style>
""", unsafe_allow_html=True)

# ============================================================================
# SIDEBAR
# ============================================================================
with st.sidebar:
    st.title("💳 SPENDLY")
    st.caption("Credit Card Spend Analyser")
    st.divider()

    st.markdown("**Pipeline status**")
    files_to_check = {
        "train.csv": _path("data", "processed", "train.csv"),
        "anomaly_df.csv": _path("outputs", "anomaly_df.csv"),
        "cluster_labels.csv": _path("outputs", "cluster_labels.csv"),
        "forecast.csv": _path("outputs", "forecast.csv"),
        "training_loss.png": _path("outputs", "training_loss.png"),
    }
    for name, fpath in files_to_check.items():
        exists = os.path.exists(fpath)
        icon = "✅" if exists else "❌"
        st.markdown(f"{icon} `{name}`")

    st.divider()
    st.caption("SPENDLY · Team Project")

# ============================================================================
# LOAD ALL DATA
# ============================================================================
train_df = _read_csv("data/processed/train.csv")
anomaly_df = _read_csv("outputs/anomaly_df.csv")
cluster_df = _read_csv("outputs/cluster_labels.csv")
forecast_df = _read_csv("outputs/forecast.csv")

# ============================================================================
# TABS
# ============================================================================
tab_overview, tab_cls, tab_anom, tab_forecast = st.tabs(
    ["📊 Overview", "🤖 Classification", "🚨 Anomalies", "📈 Forecast"]
)


# ----------------------------------------------------------------------------
# TAB 1 — OVERVIEW
# ----------------------------------------------------------------------------
with tab_overview:
    st.markdown('<p class="section-header">SPENDLY — Credit Card Spend Intelligence Dashboard</p>',
                unsafe_allow_html=True)

    if train_df is not None:
        # -- KPI cards --------------------------------------------------------
        total_spend = train_df["amount_raw"].sum()
        num_txn = len(train_df)
        top_category = train_df.groupby("exp_type")["amount_raw"].sum().idxmax()
        num_anomalies = len(anomaly_df) if anomaly_df is not None else "—"
        date_range_str = (
            f"{train_df['date'].min()} → {train_df['date'].max()}"
            if "date" in train_df.columns else "—"
        )

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("💰 Total Spend (train)", f"₹{total_spend:,.0f}")
        c2.metric("🧾 Transactions", f"{num_txn:,}")
        c3.metric("🏆 Top Category", top_category)
        c4.metric("🚨 Anomalies Detected", num_anomalies)

        st.caption(f"Date range in training data: {date_range_str}")
        st.divider()

        # -- Spend by category -----------------------------------------------
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("**Spend by Expense Category**")
            cat_spend = (
                train_df.groupby("exp_type")["amount_raw"]
                .sum()
                .sort_values(ascending=False)
                .reset_index()
            )
            cat_spend.columns = ["Category", "Total Spend (₹)"]
            if PLOTLY_OK:
                fig = px.bar(
                    cat_spend, x="Category", y="Total Spend (₹)",
                    color="Category",
                    color_discrete_sequence=px.colors.qualitative.Set2,
                )
                fig.update_layout(showlegend=False, height=320,
                                  margin=dict(t=10, b=10))
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.bar_chart(cat_spend.set_index("Category"))

        with col2:
            st.markdown("**Spend Distribution by Card Type**")
            card_spend = (
                train_df.groupby("card_type")["amount_raw"]
                .sum()
                .reset_index()
            )
            card_spend.columns = ["Card Type", "Total Spend (₹)"]
            if PLOTLY_OK:
                fig = px.pie(
                    card_spend, names="Card Type", values="Total Spend (₹)",
                    color_discrete_sequence=px.colors.qualitative.Pastel,
                    hole=0.4,
                )
                fig.update_layout(height=320, margin=dict(t=10, b=10))
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.dataframe(card_spend)

        # -- Spend over time --------------------------------------------------
        st.markdown("**Monthly Spend Over Time**")
        train_df["date_parsed"] = pd.to_datetime(train_df["date"], errors="coerce")
        monthly = (
            train_df.groupby(train_df["date_parsed"].dt.to_period("M"))["amount_raw"]
            .sum()
            .reset_index()
        )
        monthly["date_parsed"] = monthly["date_parsed"].astype(str)
        monthly.columns = ["Month", "Total Spend (₹)"]

        if PLOTLY_OK:
            fig = px.line(
                monthly, x="Month", y="Total Spend (₹)",
                markers=True,
                color_discrete_sequence=["#667eea"],
            )
            fig.update_layout(height=280, margin=dict(t=10, b=10))
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.line_chart(monthly.set_index("Month"))

    else:
        st.warning("Run `python src/preprocess.py` first to generate `data/processed/train.csv`.")


# ----------------------------------------------------------------------------
# TAB 2 — CLASSIFICATION
# ----------------------------------------------------------------------------
with tab_cls:
    st.markdown('<p class="section-header">Random Forest — Expense Category Classifier</p>',
                unsafe_allow_html=True)

    model_path = _path("models", "rf_model.pkl")
    model_exists = os.path.exists(model_path) and JOBLIB_OK

    if model_exists:
        try:
            rf_model = joblib.load(model_path)

            st.success("Model loaded successfully from `models/rf_model.pkl`")

            # -- Category mapping (from preprocess.py contract) --------------
            EXP_TYPES = ["Bills", "Entertainment", "Food", "Fuel", "Grocery", "Travel"]
            CITIES = ["Ahmedabad, India", "Bengaluru, India", "Chennai, India",
                      "Delhi, India", "Greater Mumbai, India", "Kolkata, India"]
            CARD_TYPES = ["Gold", "Platinum", "Silver", "Signature"]
            GENDERS = ["F", "M"]

            st.markdown("#### Predict Expense Category")
            st.caption("Enter transaction details to classify the expense type.")

            c1, c2, c3 = st.columns(3)
            with c1:
                amount = st.number_input("Amount (₹)", min_value=1.0, value=5000.0, step=100.0)
                city = st.selectbox("City", CITIES)
            with c2:
                card = st.selectbox("Card Type", CARD_TYPES)
                gender = st.selectbox("Gender", GENDERS)
            with c3:
                month = st.slider("Month", 1, 12, 6)
                dow = st.slider("Day of Week (0=Mon)", 0, 6, 2)
                week = st.slider("Week Number", 1, 52, 26)

            if st.button("🔍 Predict Category", type="primary"):
                # Build feature vector matching categorise.py training columns
                city_enc = CITIES.index(city) if city in CITIES else 0
                card_enc = CARD_TYPES.index(card) if card in CARD_TYPES else 0
                gen_enc = 0 if gender == "F" else 1

                # amount_norm: rough estimate using train max (₹1,000,000 assumed)
                amount_norm = min(amount / 1_000_000.0, 1.0)

                features = pd.DataFrame([[
                    amount_norm, dow, month, week,
                    card_enc, gen_enc, city_enc
                ]], columns=[
                    "amount_norm", "day_of_week", "month", "week_number",
                    "card_type_encoded", "gender_encoded", "city_encoded"
                ])

                pred_encoded = rf_model.predict(features)[0]
                pred_label = EXP_TYPES[pred_encoded] if pred_encoded < len(EXP_TYPES) else str(pred_encoded)

                try:
                    proba = rf_model.predict_proba(features)[0]
                    st.success(f"**Predicted category: {pred_label}**")
                    st.markdown("**Confidence scores:**")
                    proba_df = pd.DataFrame({
                        "Category": EXP_TYPES[:len(proba)],
                        "Confidence": [f"{p*100:.1f}%" for p in proba]
                    })
                    st.dataframe(proba_df, use_container_width=True, hide_index=True)
                except Exception:
                    st.success(f"**Predicted category: {pred_label}**")

            # -- Feature importance -----------------------------------------
            st.divider()
            st.markdown("#### Feature Importance")
            feat_names = ["amount_norm", "day_of_week", "month", "week_number",
                          "card_type_encoded", "gender_encoded", "city_encoded"]
            try:
                importances = rf_model.feature_importances_
                fi_df = pd.DataFrame({
                    "Feature": feat_names[:len(importances)],
                    "Importance": importances
                }).sort_values("Importance", ascending=False)

                if PLOTLY_OK:
                    fig = px.bar(fi_df, x="Importance", y="Feature",
                                 orientation="h",
                                 color="Importance",
                                 color_continuous_scale="Blues")
                    fig.update_layout(height=300, margin=dict(t=10, b=10),
                                      coloraxis_showscale=False)
                    st.plotly_chart(fig, use_container_width=True)
                else:
                    st.bar_chart(fi_df.set_index("Feature"))
            except Exception as e:
                st.info(f"Feature importance not available: {e}")

        except Exception as e:
            st.error(f"Error loading model: {e}")

    else:
        st.info(
            "**Model not yet available.**\n\n"
            "To generate it, run `python src/categorise.py`.\n\n"
            "This will train the Random Forest classifier and save it to `models/rf_model.pkl`."
        )
        # Show what the model should do
        st.markdown("#### What this tab will show")
        st.markdown("""
        - **Transaction input form** — enter amount, city, card type, gender, date info
        - **Predicted expense category** — Bills / Entertainment / Food / Fuel / Grocery / Travel
        - **Confidence scores** — probability per class from the Random Forest
        - **Feature importance chart** — which features drive the classification most
        """)

        if train_df is not None:
            st.markdown("#### Category distribution in training data")
            cat_dist = train_df["exp_type"].value_counts().reset_index()
            cat_dist.columns = ["Category", "Count"]
            if PLOTLY_OK:
                fig = px.bar(cat_dist, x="Category", y="Count",
                             color="Category",
                             color_discrete_sequence=px.colors.qualitative.Set2)
                fig.update_layout(showlegend=False, height=280,
                                  margin=dict(t=10, b=10))
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.bar_chart(cat_dist.set_index("Category"))


# ----------------------------------------------------------------------------
# TAB 3 — ANOMALIES
# ----------------------------------------------------------------------------
with tab_anom:
    st.markdown('<p class="section-header">Anomaly Detection — Z-score & IQR · K-Means Clustering</p>',
                unsafe_allow_html=True)

    # -- Anomaly table --------------------------------------------------------
    if anomaly_df is not None:
        st.markdown(f"**{len(anomaly_df)} anomalous months detected** across all expense categories")

        col1, col2, col3 = st.columns(3)
        col1.metric("Total Anomalies", len(anomaly_df))
        col2.metric("Z-score flagged", len(anomaly_df[anomaly_df["method"] == "zscore"]))
        col3.metric("IQR only flagged", len(anomaly_df[anomaly_df["method"] == "iqr"]))

        st.markdown("#### Flagged Anomalies")

        # Filter controls
        cats = ["All"] + sorted(anomaly_df["exp_type"].unique().tolist())
        sel_cat = st.selectbox("Filter by category", cats, key="anom_filter")
        disp = anomaly_df if sel_cat == "All" else anomaly_df[anomaly_df["exp_type"] == sel_cat]

        # Colour-code z_score column
        def highlight_z(val):
            if pd.isna(val):
                return ""
            if abs(val) > 5:
                return "background-color: #ffcccc"
            if abs(val) > 3:
                return "background-color: #fff3cd"
            return ""

        styled = disp.style.applymap(highlight_z, subset=["z_score"])
        st.dataframe(styled, use_container_width=True, hide_index=True)

        # -- Anomaly bar chart ------------------------------------------------
        st.markdown("#### Anomaly Count per Category")
        anom_count = anomaly_df["exp_type"].value_counts().reset_index()
        anom_count.columns = ["Category", "Anomaly Count"]
        if PLOTLY_OK:
            fig = px.bar(anom_count, x="Category", y="Anomaly Count",
                         color="Category",
                         color_discrete_sequence=px.colors.qualitative.Set1)
            fig.update_layout(showlegend=False, height=280,
                              margin=dict(t=10, b=10))
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.bar_chart(anom_count.set_index("Category"))

    else:
        st.warning("Run `python src/patterns.py` to generate `outputs/anomaly_df.csv`.")

    st.divider()

    # -- Cluster labels -------------------------------------------------------
    st.markdown("#### K-Means Clustering — Monthly Spend Behaviour (k=3)")
    if cluster_df is not None:
        col1, col2 = st.columns([1, 1])

        with col1:
            st.markdown("**Monthly cluster assignments**")
            st.dataframe(cluster_df, use_container_width=True, hide_index=True)

        with col2:
            st.markdown("**Cluster distribution**")
            clust_count = (
                cluster_df.groupby(["cluster_id", "cluster_label"])
                .size()
                .reset_index(name="count")
            )
            if PLOTLY_OK:
                fig = px.pie(
                    clust_count,
                    names="cluster_label",
                    values="count",
                    color_discrete_sequence=px.colors.qualitative.Pastel,
                    hole=0.35,
                )
                fig.update_layout(height=300, margin=dict(t=10, b=10))
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.bar_chart(clust_count.set_index("cluster_label")["count"])
    else:
        st.warning("Run `python src/patterns.py` to generate `outputs/cluster_labels.csv`.")


# ----------------------------------------------------------------------------
# TAB 4 — FORECAST
# ----------------------------------------------------------------------------
with tab_forecast:
    st.markdown('<p class="section-header">LSTM Forecasting — 7-Week Spend Predictions</p>',
                unsafe_allow_html=True)

    if forecast_df is not None:
        forecast_df["date"] = pd.to_datetime(forecast_df["date"])
        categories = [c for c in forecast_df.columns if c != "date"]

        # -- Forecast KPIs ----------------------------------------------------
        st.markdown("#### 7-week forecast (normalized spend per category)")
        cols = st.columns(len(categories))
        for i, cat in enumerate(categories):
            trend = forecast_df[cat].iloc[-1] - forecast_df[cat].iloc[0]
            arrow = "↑" if trend > 0 else "↓"
            cols[i].metric(
                label=cat,
                value=f"{forecast_df[cat].mean():.3f}",
                delta=f"{arrow} {abs(trend):.3f}",
            )

        st.divider()

        # -- Line chart -------------------------------------------------------
        st.markdown("#### Forecast trend by category")

        if PLOTLY_OK:
            fig = go.Figure()
            colors = px.colors.qualitative.Set2
            for i, cat in enumerate(categories):
                fig.add_trace(go.Scatter(
                    x=forecast_df["date"],
                    y=forecast_df[cat],
                    mode="lines+markers",
                    name=cat,
                    line=dict(color=colors[i % len(colors)], width=2),
                    marker=dict(size=6),
                ))
            fig.update_layout(
                height=380,
                margin=dict(t=10, b=10),
                xaxis_title="Date",
                yaxis_title="Predicted Amount (normalized)",
                legend=dict(orientation="h", yanchor="bottom", y=1.02),
            )
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.line_chart(forecast_df.set_index("date")[categories])

        st.caption(
            "⚠️ Note: Values are in normalized scale (amount_norm). "
            "Multiply by max training spend (~₹1,000,000) for approximate real amounts."
        )

        # -- Raw table --------------------------------------------------------
        with st.expander("View raw forecast data"):
            show_df = forecast_df.copy()
            show_df["date"] = show_df["date"].dt.strftime("%Y-%m-%d")
            st.dataframe(show_df, use_container_width=True, hide_index=True)

    else:
        st.warning("Run `python src/forecast.py` to generate `outputs/forecast.csv`.")

    # -- Training loss plot ---------------------------------------------------
    st.divider()
    st.markdown("#### LSTM Training Loss Curve")
    loss_path = _path("outputs", "training_loss.png")
    if os.path.exists(loss_path):
        st.image(loss_path, caption="Train vs Validation Loss over epochs", use_column_width=True)
        st.success(
            "Train and validation loss track closely together — "
            "no significant overfitting detected."
        )
    else:
        st.info("Training loss plot will appear here once `forecast.py` has been run.")

